### ISSUE TITLE
mergeToFile not working because on input and out sar parameters not matching

### ISSUE THREAD

**Issue by apprisingapps** [fluent-ffmpeg/node-fluent-ffmpeg#414]
I am attempting to merge two different videos using mergeToFile().

Code below:
var twoMerged = function (one, two){
    setTimeout(function(){
        new FfmpegCommand(one).addOption('-strict', 'experimental')
            .input(two).addOption('-strict', 'experimental')
            .on('end', function() {
                console.log('files have been merged succesfully');
            })
            .on('error', function(err, stdout, stderr) {
                console.log(" =====Convert Video Failed======");
                console.log(err);
                console.log("stdout: " + stdout);
                console.log("stderr: " + stderr);
            })
            .mergeToFile('twoTest.mp4', './temp');
    }, 5000)

I get the following error:

input link in1:v0 parameters ('size 1920x1080', SAR(10:11) do not match the cooresponding output link in:vo parameters size 1920x1080', SAR(57600:633391).

I had this error before I used the setsar filter to change the video sar on both videos in case that was the error, but did not solve the problem.  I know you are busy, thanks for any thoughts.  As a side issue, do you know a good intermediate codec to use with ffmpeg that works well with alpha?  Thanks

**Comment by njoyard** [comment]
This should be solved when adding `setsar` filters. What's the error you're getting in that case?
Additionaly, a SAR of 57600:633391 seems really weird (that means each pixel in the video is more than 10x taller than it is wide).

As for your codec question, I don't have an answer unfortunately (but maybe someone else does).

**Comment by njoyard** [comment]
Oh, my bad, you *cannot* use filters with mergeToFile, because internally it uses a complex filtergraph.
My advice would be to do the merge manually by copying the code from mergeToFile (in lib/recipes.js) and changing the complex filtergraph to add setsar.

**Comment by apprisingapps** [comment]
I will give that a shot today.  Thanks for the quick responses.

**Comment by apprisingapps** [comment]
Worked.  Thanks for the lookout.

**Comment by utsavbhagat172** [comment]
I'm still having issues with this. Can you provide me with a code snippet of the solution @apprisingapps ?

**Comment by anonrig** [comment]
@apprisingapps can you share your solution with us?
